### ISSUE TITLE
Recommended data model changes

### ISSUE THREAD

**Issue by arwhyte** [p1ho/si-664-final#1]
### UNSD data tables
I recommend that you stay with the current approach for modeling the UNSD country code data, i.e., use of a `location` table that links each `country_area` to its regional affiliations.  That way you can do a data dump of the existing UNSD tables in the unesco_heritage_sites database and then do an import into your final project database.  Otherwise, you saddle yourself with more work than is necessary for a data model that does not improve on the existing approach.

#### Example: mysqldump of individual tables.
```
mysqldump -u<username> unesco_heritage_sites country_area dev_status location planet region sub_region intermediate_region  > unsd_tables.sql
```

### Database names
Change `meteorites_country_linker` to `meteorite_landing`.  The latter name more accurately describes the nature of the data contained in the table.

### Property names
Follow Simon Holywell's [SQL Style Guide](https://www.sqlstyle.guide/) naming practices.  Change all your `id` property names to `<table_name>_id`.

**Comment by p1ho** [comment]
Hello, thank you so much for your suggestions.

I have followed your instructions and updated the db design.
Please see if this is better.

![data_model](https://user-images.githubusercontent.com/22629067/49471577-41e18f80-f7db-11e8-8915-842c7cb7f2e6.png)

**Comment by arwhyte** [comment]
A few fixes required: `meteorite_landing.meteorite_class_country_area` primary key.  Change name to `meteorite_landing_id` and change data type to `INTEGER`.

Also add the suffix `_id` to the two foreign keys in the `meteorite_landing` table:
* `meteorite_class_id`
* `country_area_id`

and in the `country_area` table: change foreign key names to 
* `location_id`
* `dev_status_id`.

The VARCHAR(65535) data types can be changed to TEXT.

**Comment by p1ho** [comment]
done!
![data_model](https://user-images.githubusercontent.com/22629067/49683003-e4c03500-fa8b-11e8-9ee0-8ba64e5402f1.png)

**Comment by arwhyte** [comment]
Looks good.  You can close this issue.
